language: r
cache: packages

env:
 global:
   - secure: "iw+w4PKDNDSR+/5qYXoRDDv9urX7dAPP3+7suhEDE+ZLLZprCRaZ+d4io/PeDOW6ruCOvGbN6VbQVea5n4D3Hy2u8r1pn+UB1qCp3U+UjBrY2q7hAdHo443+SRvNAzIBbf4W+8E2CPzT3cE2bgvkhPb1jwjQKPD9wXK1MvyzN3smLfC60xsWPlJ2jCYL1MuDQV2jxFpuFgQNTfo9bzpeZtU4s6yDAy2ifTHHZyqSEuDJ0vFwvb6tuCOco/Dp3WhEps0zNAixuL+ezINrCh44HdA9SRTd6FA+55UbxdIw3SI6YN5CO3cIaqVoLYZVIkxNm6/8iMRrD3lqF2Ch6Lt4nZ+f7AJC26VLQORyFXrqiznn3yiwTV0CPkF4NUeo8+hp7LXe616l3Es3Ek+UqlNXWYPIUpCm4EcelgWDQnrag72W5dq/BUsh/vc+tjbHGJ2qMyTx3mkBa8uaXkThj/8N1ZoxmG7JjrE1jaDQyZYm5B1uh3mHt3mJSzxIV007SDdbDp6XKH6LOgFtnL2OqnHGBrmQ9AQM/IgoZi3P7eScFQ/K3UHHPd7AvcsiZ0lYiubgctpgmfm6ZY7kScHTC9zMW5qVog1o96JdQKR5GgpCEbw2mi5J58qd04VpNZcHQOPacCM4gwLBHKAkJMmc32m7eZlTa5dP9y3ztZY5dp6kco8="

